services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # env_file:
    #   - .envrc
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: server
    restart: always
    tty: true
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - PORT=8080
    env_file:
      - .envrc
    ports:
      - '8080:8080'
    volumes: # if there's any new files containing sources, add them as volumes
      - ./src:/app/src
      - ./prisma:/app/prisma
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    restart: unless-stopped

volumes:
  db-data:
